# This workflow will test a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Unit Tests

on:
  - pull_request
  
concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test-ios:
    name: Build and Test (iOS 18.1)
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: "/Applications/Xcode_16.1.app/Contents/Developer"

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4
      
    # Build
    - name: Build
      run: |
        xcodebuild build\
          -scheme EDXMobileAnalytics \
          -destination 'platform=iOS Simulator,name=iPhone SE (3rd generation)' \
          -skipPackagePluginValidation \
          -skipMacroValidation 
      
    # Run Unit Tests
    - name: Run tests
      run: |
        xcodebuild test \
          -scheme EDXMobileAnalytics \
          -destination "OS=18.1,name=iPhone 16 Pro" \
          -skipPackagePluginValidation \
          -skipMacroValidation
